[project]
name = "jeopardy"
version = "0.1.0"
description = "Lightweight FastAPI webapp for hosting a configurable Jeopardy game."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "jinja2>=3.1.4",
    "pyyaml>=6.0.2",
]
